# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'random-user' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for random-user
  pod 'Kingfisher'

  target 'random-userTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'random-userUITests' do
    # Pods for testing
  end

end
